name: Docker Image Integration Test

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker image to pull and run'
        required: true
      port:
        description: 'Port to expose (default: 8080)'
        required: false
        default: '8080'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker Image
        run: docker pull ${{ github.event.inputs.docker_image }}

      - name: Run Docker Container
        run: |
          docker run -d -p ${{ github.event.inputs.port }}:${{ github.event.inputs.port }} ${{ github.event.inputs.docker_image }}

      - name: Start ngrok for 1h
        run: |
           wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
           tar xvzf ./ngrok-v3-stable-linux-amd64.tgz
           ./ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
           ./ngrok http ${{ github.event.inputs.port }} &
           sleep 5
           curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
           echo "ngrok URL: $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
           timeout 1h wait