name: IntegrationTest

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo to checkout'
        required: true
      ref:
        description: 'Branch, tag or SHA'
        required: true
        default:: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.PAT }}

      - name: Setup ngrok
        run: |
           wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
           tar xvzf ./ngrok-v3-stable-linux-amd64.tgz
           ./ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Start ngrok tunnel
        run: ( timeout 1h ./ngrok http 8080 ) &
        shell: bash

      - name: Print tunnel URL
        run: |
          sleep 5
          echo "ngrok URL: $(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
          
      - name: Spin Up Docker Container
        run: |
           export INTEGRATION_TESTING=true
           export SIWA_APPLICATION_IDENTIFIER=${{ secrets.SIWA_APPLICATION_IDENTIFIER }}
           export JWT_SECRET=${{ secrets.JWT_SECRET }}
           docker compose up
