name: IntegrationTest

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo to checkout'
        required: true
      ref:
        description: 'Branch, tag or SHA'
        required: true
        default:: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.PAT }}

      - name: Spin Up Docker Container
        run: docker compose up -d

      - uses: luisboto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 1h
          port: 8080
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          tunnel_type: http
