name: IntegrationTest

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo to checkout'
        required: true
      ref:
        description: 'Branch, tag or SHA'
        required: true
        default:: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
          token: ${{ secrets.PAT }}

      - name: Spin Up Docker Container
        run: docker compose up -d

      - name: Start ngrok for 1h
        run: |
           wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
           tar xvzf ./ngrok-v3-stable-linux-amd64.tgz
           ./ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
           timeout 1h ./ngrok http 8080
